//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseLinker_Products_Multitool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseLinker_Products_Multitool.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie dodano {a} z {b} produktów!.
        /// </summary>
        internal static string AddedProductsInfo {
            get {
                return ResourceManager.GetString("AddedProductsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spośród {a} produktów odnaleziono łącznie {b} {c}, których jest więcej niż jeden!.
        /// </summary>
        internal static string CheckDuplicatesEndInfo {
            get {
                return ResourceManager.GetString("CheckDuplicatesEndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie usunięto {a} z {b} produktów!.
        /// </summary>
        internal static string DeletedProductsInfo {
            get {
                return ResourceManager.GetString("DeletedProductsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobrano szczegółowe informacje o {a} produktach....
        /// </summary>
        internal static string DownloadedInfoAboutXProducts {
            get {
                return ResourceManager.GetString("DownloadedInfoAboutXProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobrano {a} produktów....
        /// </summary>
        internal static string DownloadedXProducts {
            get {
                return ResourceManager.GetString("DownloadedXProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy rozumiesz powyższe oraz chcesz kontynuować kopiowanie produktów?.
        /// </summary>
        internal static string DoYouUnderstandAndAgree {
            get {
                return ResourceManager.GetString("DoYouUnderstandAndAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pusta listów produktów!.
        /// </summary>
        internal static string EmptyListOfProducts {
            get {
                return ResourceManager.GetString("EmptyListOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz token API konta BaseLinker (Moje konto &gt; API &gt; Twój token API) i zatwierdź wciskając ENTER.
        /// </summary>
        internal static string EnterAPIToken {
            get {
                return ResourceManager.GetString("EnterAPIToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz ID kategorii produktów (Magazyn BaseLinker &gt; Kategorie &gt; [Twoja kategoria] &gt; [W adresie strony pojawi się na końcu id kategorii]) i zatwierdź wciskając ENTER.
        /// </summary>
        internal static string EnterCategory {
            get {
                return ResourceManager.GetString("EnterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz ilość nowych produktów i zatwierdź wciskając ENTER.
        /// </summary>
        internal static string EnterQuantityOfNewProducts {
            get {
                return ResourceManager.GetString("EnterQuantityOfNewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas pobierania szczegółowych informacji o produktach!.
        /// </summary>
        internal static string ErrorWhenDownloadFullProducts {
            get {
                return ResourceManager.GetString("ErrorWhenDownloadFullProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas pobierania listy produktów!.
        /// </summary>
        internal static string ErrorWhenDownloadProducts {
            get {
                return ResourceManager.GetString("ErrorWhenDownloadProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjście.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaleziono zduplikowane {a}:.
        /// </summary>
        internal static string FoundDuplicate {
            get {
                return ResourceManager.GetString("FoundDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak sprawdzać czy produkt jest zduplikowany?.
        /// </summary>
        internal static string HowToCheckDuplicates {
            get {
                return ResourceManager.GetString("HowToCheckDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer magazynowy - SKU.
        /// </summary>
        internal static string HowToCheckDuplicates1 {
            get {
                return ResourceManager.GetString("HowToCheckDuplicates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        internal static string HowToCheckDuplicates2 {
            get {
                return ResourceManager.GetString("HowToCheckDuplicates2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string HowToCheckDuplicates3 {
            get {
                return ResourceManager.GetString("HowToCheckDuplicates3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak usuwać zdublowane produkty?.
        /// </summary>
        internal static string HowToDeleteDuplicates {
            get {
                return ResourceManager.GetString("HowToDeleteDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spośród zduplikowanych produktów pozostaw jeden z najwyższym ID (najnowszy dodany do kategorii produktów).
        /// </summary>
        internal static string HowToDeleteDuplicates1 {
            get {
                return ResourceManager.GetString("HowToDeleteDuplicates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spośród zduplikowanych produktów pozostaw jeden z najniższym ID (najstarszy dodany do kategorii produktów).
        /// </summary>
        internal static string HowToDeleteDuplicates2 {
            get {
                return ResourceManager.GetString("HowToDeleteDuplicates2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWAGA! Przez ograniczenia API przesyłane zdjęcia ułożą się po kolei! Przykładowo jeśli produkt posiada zdjęcie główne, zdjęcie dodatkowe 7 oraz zdjęcie dodatkowe 10, to kopia tego produktu będzie miała zdjęcie główne, zdjęcie dodatkowe 1 oraz zdjęcie dodatkowe 2! Jeśli produkt posiada zdjęcie dodatkowe 5 i zdjęcie dodatkowe 12  to kopia tego produktu będzie miała zdjęcie główne i zdjęcie dodatkowe 1!.
        /// </summary>
        internal static string InfoAboutImages {
            get {
                return ResourceManager.GetString("InfoAboutImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWAGA! Jeśli produkt posiada wariant bez przypisanej ceny, w wariancie w skopiowanym produkcie będzie cena 1,00!.
        /// </summary>
        internal static string InfoAboutVariantsPrices {
            get {
                return ResourceManager.GetString("InfoAboutVariantsPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie ma duplikatów!.
        /// </summary>
        internal static string InfoNoDuplicates {
            get {
                return ResourceManager.GetString("InfoNoDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy wszystkie powyższe ustawienia są poprawne?.
        /// </summary>
        internal static string IsEverythingCorrect {
            get {
                return ResourceManager.GetString("IsEverythingCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GŁÓWNE MENU.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdzanie duplikatów produktów w wybranej kategorii produktów w BaseLinker (tylko sprawdzanie, bez usuwania).
        /// </summary>
        internal static string Menu1 {
            get {
                return ResourceManager.GetString("Menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie duplikatów produktów w wybranej kategorii produktów w BaseLinker.
        /// </summary>
        internal static string Menu2 {
            get {
                return ResourceManager.GetString("Menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiowanie wszystkich produktów z jednej kategorii do drugiej (możliwy przesył między kontami BaseLinker).
        /// </summary>
        internal static string Menu3 {
            get {
                return ResourceManager.GetString("Menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiowanie całego magazynu produktów (with all categories, with all products, etc.) z jednego konta BaseLinker do drugiego.
        /// </summary>
        internal static string Menu4 {
            get {
                return ResourceManager.GetString("Menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masowe generowanie nowych produktów w wybranej kategorii produktów w BaseLinker (dla testów).
        /// </summary>
        internal static string Menu5 {
            get {
                return ResourceManager.GetString("Menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie. Wróć do menu głównego!.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teraz wprowadź dane drugiego konta BaseLinker....
        /// </summary>
        internal static string NowEnterSecondBL {
            get {
                return ResourceManager.GetString("NowEnterSecondBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość produktów do usunięcia.
        /// </summary>
        internal static string NumberOfProductsToDeleteQuestion {
            get {
                return ResourceManager.GetString("NumberOfProductsToDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wciśnij dowolny klawisz aby wrócić do menu głównego....
        /// </summary>
        internal static string PressAnythingToBackToMenu {
            get {
                return ResourceManager.GetString("PressAnythingToBackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie ponoszę odpowiedzialności za szkody wyrządzone na koncie BaseLinker spowodowane nieumiejętnym użyciem programu!.
        /// </summary>
        internal static string ResponsibilityInfo {
            get {
                return ResourceManager.GetString("ResponsibilityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęto usuwanie zduplikowanych produktów....
        /// </summary>
        internal static string StartedDeleteProduct {
            get {
                return ResourceManager.GetString("StartedDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęto pobieranie listy produktów..
        /// </summary>
        internal static string StartedGetProductsList {
            get {
                return ResourceManager.GetString("StartedGetProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęto pobieranie szczegółowych informacji o produktach..
        /// </summary>
        internal static string StartedGetProductsListFull {
            get {
                return ResourceManager.GetString("StartedGetProductsListFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wariant.
        /// </summary>
        internal static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podałeś niepoprawną wartość, wybierz pozycję z menu wpisując jej numer..
        /// </summary>
        internal static string WrongMenuInput {
            get {
                return ResourceManager.GetString("WrongMenuInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak, zaczynaj!.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje ustawienia.
        /// </summary>
        internal static string YourOptions {
            get {
                return ResourceManager.GetString("YourOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token API.
        /// </summary>
        internal static string YourOptionsAPI {
            get {
                return ResourceManager.GetString("YourOptionsAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token API źródłowego konta.
        /// </summary>
        internal static string YourOptionsAPISource {
            get {
                return ResourceManager.GetString("YourOptionsAPISource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token API docelowego konta.
        /// </summary>
        internal static string YourOptionsAPITarget {
            get {
                return ResourceManager.GetString("YourOptionsAPITarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria produktów.
        /// </summary>
        internal static string YourOptionsCategory {
            get {
                return ResourceManager.GetString("YourOptionsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Źródłowa kategoria produktów.
        /// </summary>
        internal static string YourOptionsCategorySource {
            get {
                return ResourceManager.GetString("YourOptionsCategorySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docelowa kategoria produktów.
        /// </summary>
        internal static string YourOptionsCategoryTarget {
            get {
                return ResourceManager.GetString("YourOptionsCategoryTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz sprawdzania produktów.
        /// </summary>
        internal static string YourOptionsCheckKey {
            get {
                return ResourceManager.GetString("YourOptionsCheckKey", resourceCulture);
            }
        }
    }
}
