//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseLinker_Products_Multitool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseLinker_Products_Multitool.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz token API konta BaseLinker (Moje konto &gt; API &gt; Twój token API).
        /// </summary>
        internal static string EnterAPIToken {
            get {
                return ResourceManager.GetString("EnterAPIToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz ID kategorii produktów (Magazyn BaseLinker &gt; Kategorie &gt; [Twoja kategoria] &gt; [W adresie strony pojawi się na końcu id kategorii]).
        /// </summary>
        internal static string EnterCategory {
            get {
                return ResourceManager.GetString("EnterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjście.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak sprawdzać czy produkt jest zduplikowany?.
        /// </summary>
        internal static string HowToCheckDuplicates {
            get {
                return ResourceManager.GetString("HowToCheckDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer magazynowy - SKU.
        /// </summary>
        internal static string HowToCheckDuplicates1 {
            get {
                return ResourceManager.GetString("HowToCheckDuplicates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        internal static string HowToCheckDuplicates2 {
            get {
                return ResourceManager.GetString("HowToCheckDuplicates2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string HowToCheckDuplicates3 {
            get {
                return ResourceManager.GetString("HowToCheckDuplicates3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy powyższe ustawienia są poprawne?.
        /// </summary>
        internal static string IsEverythingCorrect {
            get {
                return ResourceManager.GetString("IsEverythingCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GŁÓWNE MENU.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdzanie czy w magazynie produktów BaseLinkera występują duplikaty produktów.
        /// </summary>
        internal static string Menu1 {
            get {
                return ResourceManager.GetString("Menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie duplikatów w magazynie produktów BaseLinkera.
        /// </summary>
        internal static string Menu2 {
            get {
                return ResourceManager.GetString("Menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przenoszenie magazynu produktów z jednego konta BaseLinker do drugiego.
        /// </summary>
        internal static string Menu3 {
            get {
                return ResourceManager.GetString("Menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie. Wróć do menu głównego!.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podałeś niepoprawną wartość, wybierz pozycję z menu wpisując jej numer.  Wciśnij dowolny klawisz aby wrócić do menu głównego!.
        /// </summary>
        internal static string WrongMenuInput {
            get {
                return ResourceManager.GetString("WrongMenuInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak, zaczynaj!.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje ustawienia.
        /// </summary>
        internal static string YourOptions {
            get {
                return ResourceManager.GetString("YourOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token API.
        /// </summary>
        internal static string YourOptionsAPI {
            get {
                return ResourceManager.GetString("YourOptionsAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria produktów.
        /// </summary>
        internal static string YourOptionsCategory {
            get {
                return ResourceManager.GetString("YourOptionsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz sprawdzania produktów.
        /// </summary>
        internal static string YourOptionsCheckKey {
            get {
                return ResourceManager.GetString("YourOptionsCheckKey", resourceCulture);
            }
        }
    }
}
